name: Issue created - Virtuemart Payment Gateway-

on:
  issues:
    types: [opened]

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue to Freshdesk
        run: |
          curl -v -u "${{ secrets.FRESHDESK_API_KEY }}:X" \
          -H "Content-Type: application/json" \
          -X POST "https://${{ secrets.FRESHDESK_DOMAIN }}/api/v2/tickets" \
          -d '{
            "subject": "${{ github.event.issue.title }}",
            "description": "${{ github.event.issue.body }}",
            "email": "${{ secrets.SUPPORT_EMAIL }}",
            "priority": 1,
            "status": 2,
            "tags": ["github-issue"]
          }'
